// <auto-generated />
namespace Student_Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removedrequiredfromusername : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedrequiredfromusername));
        
        string IMigrationMetadata.Id
        {
            get { return "202007031719201_removed required from username"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
