// <auto-generated />
namespace Student_Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_rank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_rank));
        
        string IMigrationMetadata.Id
        {
            get { return "202007022348505_update_rank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
