// <auto-generated />
namespace Student_Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removedmothernameandfathernameforfaclty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedmothernameandfathernameforfaclty));
        
        string IMigrationMetadata.Id
        {
            get { return "202007072343330_removed mothername and fathername for faclty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
